config/routes.rb
Lime::Application.routes.draw do
  resources :dashboard, :as => "dashboards"
  resources :playground, :as => "playgrounds"

  root :to => 'dashboard#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @all_images = Dir.entries("app/assets/images")
    
    #removing non-image files
    @all_images.delete(".")
    @all_images.delete("..")
    @all_images.delete(".DS_Store")
  end
end

app/controllers/playground_controller.rb
class PlaygroundController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/playground_helper.rb
module PlaygroundHelper
end

app/views/dashboard/index.html.erb
<center id="carousel-wrapper">
  <div id="myCarousel" class="carousel slide">
    <div class="carousel-inner">
      <% @all_images.each_with_index do |image, i| %>
        <% if i == 0 %>
          <div class="active item">
            <%= image_tag image, :class => "div-carousel-image" %>
          </div>
        <% else %>
          <div class="item">
            <%= image_tag image, :class => "div-carousel-image" %>
          </div>
        <% end %>
      <% end %>
    </div>

    <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
    <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
  </div>
</center>

<div id="gallery-wrapper">
  <div class="row-fluid">
    <% @all_images.each_with_index do |image, i| %>
      <div class="span1 image-thumbnail" data-imageid="<%= i %>">
        <%= image_tag image, :class => "div-image" %>
      </div>
    <% end %>
  </div>
<div>

<script>
  $(document).ready(function(){
    $(".carousel").carousel({
      interval: false,
    });
    
    //left and right arrow keys to move the carousel
    $(document).keydown(function(e) {
      if(e.which == 37){
        $(".carousel").carousel('prev');
      }
      if(e.which == 39){
        $(".carousel").carousel('next');
      }
    });
    
    $(".image-thumbnail").on("click", function(){
      $(".carousel").carousel($(this).data("imageid"));
    });
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lime</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "bootstrap.min" %>
  <%= csrf_meta_tags %>
</head>
<body style="margin-top: 65px;">
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container-fluid">
        <%= link_to "Lime", root_path, :class => "brand" %>
        <ul class="nav">
          <% if (request.fullpath == root_path) || (request.fullpath == dashboards_path) %>
            <li class="active"><%= link_to "Dashboard", root_path %></li>
          <% else %>
            <li><%= link_to "Dashboard", root_path %></li>
          <% end %>
          
          <% if request.fullpath == playgrounds_path %>
            <li class="active"><%= link_to "Play Ground", playgrounds_path %></li>
          <% else %>
            <li><%= link_to "Play Ground", playgrounds_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>  
  
  <%= yield %>

</body>
</html>

app/views/playground/index.html.erb
<!-- make this dynamically resize using bootstrap when internet connection is available start -->
<div id="playground-hidden-div">
  
  <!-- HTML5 based Tetris here when button is clicked? -->
  
</div>
<div id="playground-main-div">
  <h1 id="playground-h1">Welcome to my Play Ground</h1>
  <strong>You usually won't find anything in here, just me playing around with some code.</strong>
  <center>
    <p>The blue pill below is for <strong>your</strong> entertainment.</p>
    <button class="btn btn-primary" id="the-blue-pill">Blue Pill</button>
  </center>
</div>
<!-- end -->


<script>
  $(document).ready(function(){
    $("#the-blue-pill").on("click", function(){
      console.log("hello");
    });
  });
</script>